name: Java CI (Manual)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          javac -d ./out src/*.java -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar"

      - name: Run JUnit tests
        run: |
          java -cp "out:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore JugadorTest
